/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "jni_define.h"
/* Header for class com_test_demo_jni_NativeInterface */

#ifndef _Included_com_test_demo_jni_NativeInterface
#define _Included_com_test_demo_jni_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_test_demo_jni_AlgorithmNativeInterface_runAlgorithm
  (JNIEnv *env, jobject clazz, jint id);

#ifdef __cplusplus
}
#endif
#endif
